platform :ios, '13.0'

use_frameworks!

target 'com.awareframework.ios.sensor.rotation_Example' do
  pod 'com.awareframework.ios.sensor.rotation', :path => '../'

  target 'com.awareframework.ios.sensor.rotation_Tests' do
    inherit! :search_paths

    
  end
end
