# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
xcode_workspace: Example/com.awareframework.ios.sensor.rotation.xcworkspace
xcode_scheme: com.awareframework.ios.sensor.rotation-Tests
xcode_destination: platform=iOS simulator, OS=12.0, name=iPhone X
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version


# - pod install --project-directory=Example
# script:
# iphonesimulator12.0  ONLY_ACTIVE_ARCH=NO | xcpretty
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.rotation.xcworkspace -scheme com.awareframework.ios.sensor.rotation-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
